# Generated by Django 5.1 on 2024-08-17 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название продукта', max_length=255, verbose_name='Название')),
                ('model', models.CharField(help_text='Модель продукта', max_length=255, verbose_name='Модель')),
                ('release_date', models.DateField(help_text='Дата выпуска продукта', verbose_name='Дата выпуска')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название сетевого узла', max_length=255, verbose_name='Название')),
                ('email', models.EmailField(help_text='Адрес электронной почты', max_length=254, verbose_name='Email')),
                ('country', models.CharField(help_text='Страна сетевого узла', max_length=100, verbose_name='Страна')),
                ('city', models.CharField(help_text='Город сетевого узла', max_length=100, verbose_name='Город')),
                ('street', models.CharField(help_text='Улица сетевого узла', max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(help_text='Номер дома сетевого узла', max_length=10, verbose_name='Номер дома')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, help_text='Задолженность по сетевому узлу', max_digits=10, verbose_name='Задолженность')),
                ('level', models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], help_text='Уровень сетевого узла', verbose_name='Уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания сетевого узла', verbose_name='Дата создания')),
                ('supplier', models.ForeignKey(blank=True, help_text='Поставщик сетевого узла', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='network.networknode', verbose_name='Поставщик')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_nodes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('products', models.ManyToManyField(help_text='Продукты сетевого узла', related_name='network_nodes', to='network.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Сетевой узел',
                'verbose_name_plural': 'Сетевые узлы',
            },
        ),
    ]
