# Generated by Django 5.1 on 2024-08-17 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networknode',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='network_node',
            field=models.ForeignKey(default=1, help_text='Сетевой узел для продукта', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='network.networknode', verbose_name='Сетевой узел'),
            preserve_default=False,
        ),
    ]
