# Generated by Django 5.1 on 2024-08-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_networknode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networknode',
            name='products',
        ),
        migrations.AddField(
            model_name='networknode',
            name='products',
            field=models.OneToOneField(help_text='Продукты сетевого узла', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.product', verbose_name='Продукты'),
        ),
    ]
