# Generated by Django 5.1 on 2024-08-21 05:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_product_network_nodes_product_network_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='city',
            field=models.CharField(help_text='Город предприятия', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='country',
            field=models.CharField(help_text='Страна предприятия', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания предприятия', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Задолженность предприятия', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Задолженность'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='email',
            field=models.EmailField(help_text='Email предприятия', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='house_number',
            field=models.CharField(help_text='Номер дома предприятия', max_length=10, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='level',
            field=models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], help_text='Уровень предприятия', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='name',
            field=models.CharField(help_text='Название предприятия', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='street',
            field=models.CharField(help_text='Улица предприятия', max_length=100, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Поставщик предприятия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='network.networknode', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='network_node',
            field=models.ForeignKey(help_text='Предприятие, производитель продукта', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='network.networknode', verbose_name='Предприятие'),
        ),
    ]
