# Generated by Django 5.1 on 2024-08-21 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_networknode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='network_node',
            field=models.ForeignKey(help_text='Предприятие, производитель продукта', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='network.networknode', verbose_name='Производитель'),
        ),
    ]
