# Generated by Django 5.1 on 2024-08-21 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_product_network_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Страна предприятия', max_length=100, verbose_name='Страна')),
                ('city', models.CharField(help_text='Город предприятия', max_length=100, verbose_name='Город')),
                ('street', models.CharField(help_text='Улица предприятия', max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(help_text='Номер дома предприятия', max_length=10, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='city',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='country',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='street',
        ),
        migrations.RemoveField(
            model_name='product',
            name='network_node',
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ManyToManyField(help_text='Предприятие, производитель продукта', related_name='products', to='network.networknode', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='networknode',
            name='address',
            field=models.ForeignKey(default=10, help_text='Адрес предприятия', on_delete=django.db.models.deletion.CASCADE, related_name='network_nodes', to='network.address', verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
